name: ectomigo github test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: ectomigo/ectomigo@v0.1.5
        name: test
        with:
          migration_paths: migrations/**/*
          patterns: '{"massive": ["javascript/**/*.js"], "pojo": ["java/**/*.java"]}'
          token: ${{ secrets.GITHUB_TOKEN }}
